services:
  database:
    container_name: postgres-db
    image: postgres:17
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_PASSWORD=root'
    volumes:
      - './volumes/ecommerce/postgres:/var/lib/postgresql/data'
